//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadCatalogService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Catalog
    {
        public tbl_Catalog()
        {
            this.tbl_bookIssueReturn = new HashSet<tbl_bookIssueReturn>();
        }
    
        public int bookid { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public Nullable<bool> isBookIssued { get; set; }
    
        public virtual ICollection<tbl_bookIssueReturn> tbl_bookIssueReturn { get; set; }
    }
}
