//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadCatalogService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bookIssueReturn
    {
        public int bookissuereturnid { get; set; }
        public Nullable<int> libraryuserid { get; set; }
        public Nullable<int> bookid { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<int> fineamount { get; set; }
    
        public virtual tbl_Catalog tbl_Catalog { get; set; }
        public virtual tbl_LibraryUser tbl_LibraryUser { get; set; }
    }
}
